# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_CalibrationFDBdAg.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QToolButton, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1899, 1092)
        self.bg_est_2 = QGroupBox(Form)
        self.bg_est_2.setObjectName(u"bg_est_2")
        self.bg_est_2.setGeometry(QRect(10, 10, 1881, 521))
        font = QFont()
        font.setPointSize(12)
        self.bg_est_2.setFont(font)
        self.bg_img_dir_path_2 = QLineEdit(self.bg_est_2)
        self.bg_img_dir_path_2.setObjectName(u"bg_img_dir_path_2")
        self.bg_img_dir_path_2.setGeometry(QRect(210, 30, 570, 31))
        self.bg_img_dir_2 = QLabel(self.bg_est_2)
        self.bg_img_dir_2.setObjectName(u"bg_img_dir_2")
        self.bg_img_dir_2.setGeometry(QRect(10, 30, 200, 31))
        self.bg_img_open_dir_2 = QToolButton(self.bg_est_2)
        self.bg_img_open_dir_2.setObjectName(u"bg_img_open_dir_2")
        self.bg_img_open_dir_2.setGeometry(QRect(790, 30, 30, 31))
        self.bg_img_load_2 = QPushButton(self.bg_est_2)
        self.bg_img_load_2.setObjectName(u"bg_img_load_2")
        self.bg_img_load_2.setGeometry(QRect(840, 29, 120, 31))
        self.bg_img_5 = QLabel(self.bg_est_2)
        self.bg_img_5.setObjectName(u"bg_img_5")
        self.bg_img_5.setGeometry(QRect(10, 180, 451, 321))
        self.bg_img_6 = QLabel(self.bg_est_2)
        self.bg_img_6.setObjectName(u"bg_img_6")
        self.bg_img_6.setGeometry(QRect(480, 180, 441, 321))
        self.bg_img_7 = QLabel(self.bg_est_2)
        self.bg_img_7.setObjectName(u"bg_img_7")
        self.bg_img_7.setGeometry(QRect(1400, 180, 441, 321))
        self.bg_img_8 = QLabel(self.bg_est_2)
        self.bg_img_8.setObjectName(u"bg_img_8")
        self.bg_img_8.setGeometry(QRect(940, 180, 441, 321))
        self.bg_noise_est_2 = QPushButton(self.bg_est_2)
        self.bg_noise_est_2.setObjectName(u"bg_noise_est_2")
        self.bg_noise_est_2.setGeometry(QRect(1050, 30, 210, 31))
        self.bg_val_est_2 = QGroupBox(self.bg_est_2)
        self.bg_val_est_2.setObjectName(u"bg_val_est_2")
        self.bg_val_est_2.setGeometry(QRect(10, 80, 1861, 71))
        self.bg_b1_2 = QLabel(self.bg_val_est_2)
        self.bg_b1_2.setObjectName(u"bg_b1_2")
        self.bg_b1_2.setGeometry(QRect(10, 30, 60, 31))
        self.bg_val_b1_2 = QLineEdit(self.bg_val_est_2)
        self.bg_val_b1_2.setObjectName(u"bg_val_b1_2")
        self.bg_val_b1_2.setGeometry(QRect(80, 30, 151, 31))
        self.bg_b2_2 = QLabel(self.bg_val_est_2)
        self.bg_b2_2.setObjectName(u"bg_b2_2")
        self.bg_b2_2.setGeometry(QRect(470, 30, 60, 31))
        self.bg_val_b2_2 = QLineEdit(self.bg_val_est_2)
        self.bg_val_b2_2.setObjectName(u"bg_val_b2_2")
        self.bg_val_b2_2.setGeometry(QRect(540, 30, 151, 31))
        self.bg_b3_2 = QLabel(self.bg_val_est_2)
        self.bg_b3_2.setObjectName(u"bg_b3_2")
        self.bg_b3_2.setGeometry(QRect(930, 30, 60, 31))
        self.bg_val_b3_2 = QLineEdit(self.bg_val_est_2)
        self.bg_val_b3_2.setObjectName(u"bg_val_b3_2")
        self.bg_val_b3_2.setGeometry(QRect(1000, 30, 151, 31))
        self.bg_val_b4_2 = QLineEdit(self.bg_val_est_2)
        self.bg_val_b4_2.setObjectName(u"bg_val_b4_2")
        self.bg_val_b4_2.setGeometry(QRect(1460, 30, 151, 31))
        self.bg_b4_2 = QLabel(self.bg_val_est_2)
        self.bg_b4_2.setObjectName(u"bg_b4_2")
        self.bg_b4_2.setGeometry(QRect(1390, 30, 60, 31))
        self.ref_est_2 = QGroupBox(Form)
        self.ref_est_2.setObjectName(u"ref_est_2")
        self.ref_est_2.setGeometry(QRect(10, 560, 1881, 521))
        self.ref_est_2.setFont(font)
        self.ref_img_dir_path_2 = QLineEdit(self.ref_est_2)
        self.ref_img_dir_path_2.setObjectName(u"ref_img_dir_path_2")
        self.ref_img_dir_path_2.setGeometry(QRect(250, 30, 551, 31))
        self.ref_img_dir_2 = QLabel(self.ref_est_2)
        self.ref_img_dir_2.setObjectName(u"ref_img_dir_2")
        self.ref_img_dir_2.setGeometry(QRect(10, 30, 230, 31))
        self.ref_img_open_dir_2 = QToolButton(self.ref_est_2)
        self.ref_img_open_dir_2.setObjectName(u"ref_img_open_dir_2")
        self.ref_img_open_dir_2.setGeometry(QRect(810, 30, 31, 31))
        self.ref_img_load_2 = QPushButton(self.ref_est_2)
        self.ref_img_load_2.setObjectName(u"ref_img_load_2")
        self.ref_img_load_2.setGeometry(QRect(860, 29, 120, 31))
        self.ref_img_5 = QLabel(self.ref_est_2)
        self.ref_img_5.setObjectName(u"ref_img_5")
        self.ref_img_5.setGeometry(QRect(10, 180, 451, 321))
        self.ref_img_6 = QLabel(self.ref_est_2)
        self.ref_img_6.setObjectName(u"ref_img_6")
        self.ref_img_6.setGeometry(QRect(480, 180, 441, 321))
        self.ref_img_7 = QLabel(self.ref_est_2)
        self.ref_img_7.setObjectName(u"ref_img_7")
        self.ref_img_7.setGeometry(QRect(1400, 180, 441, 321))
        self.ref_img_8 = QLabel(self.ref_est_2)
        self.ref_img_8.setObjectName(u"ref_img_8")
        self.ref_img_8.setGeometry(QRect(940, 180, 441, 321))
        self.ref_rad_est_2 = QPushButton(self.ref_est_2)
        self.ref_rad_est_2.setObjectName(u"ref_rad_est_2")
        self.ref_rad_est_2.setGeometry(QRect(1060, 30, 230, 31))
        self.ref_rad_val_est_2 = QGroupBox(self.ref_est_2)
        self.ref_rad_val_est_2.setObjectName(u"ref_rad_val_est_2")
        self.ref_rad_val_est_2.setGeometry(QRect(10, 80, 1861, 71))
        self.ref_rad_b1_2 = QLabel(self.ref_rad_val_est_2)
        self.ref_rad_b1_2.setObjectName(u"ref_rad_b1_2")
        self.ref_rad_b1_2.setGeometry(QRect(10, 30, 60, 31))
        self.ref_rad_val_b1_2 = QLineEdit(self.ref_rad_val_est_2)
        self.ref_rad_val_b1_2.setObjectName(u"ref_rad_val_b1_2")
        self.ref_rad_val_b1_2.setGeometry(QRect(80, 30, 151, 31))
        self.ref_rad_b2_2 = QLabel(self.ref_rad_val_est_2)
        self.ref_rad_b2_2.setObjectName(u"ref_rad_b2_2")
        self.ref_rad_b2_2.setGeometry(QRect(470, 30, 60, 31))
        self.ref_rad_val_b2_2 = QLineEdit(self.ref_rad_val_est_2)
        self.ref_rad_val_b2_2.setObjectName(u"ref_rad_val_b2_2")
        self.ref_rad_val_b2_2.setGeometry(QRect(540, 30, 151, 31))
        self.ref_rad_b3_2 = QLabel(self.ref_rad_val_est_2)
        self.ref_rad_b3_2.setObjectName(u"ref_rad_b3_2")
        self.ref_rad_b3_2.setGeometry(QRect(930, 30, 60, 31))
        self.ref_rad_val_b3_2 = QLineEdit(self.ref_rad_val_est_2)
        self.ref_rad_val_b3_2.setObjectName(u"ref_rad_val_b3_2")
        self.ref_rad_val_b3_2.setGeometry(QRect(1000, 30, 151, 31))
        self.ref_rad_val_b4_2 = QLineEdit(self.ref_rad_val_est_2)
        self.ref_rad_val_b4_2.setObjectName(u"ref_rad_val_b4_2")
        self.ref_rad_val_b4_2.setGeometry(QRect(1460, 30, 151, 31))
        self.ref_rad_b4_2 = QLabel(self.ref_rad_val_est_2)
        self.ref_rad_b4_2.setObjectName(u"ref_rad_b4_2")
        self.ref_rad_b4_2.setGeometry(QRect(1390, 30, 60, 31))
        self.exp_status_label_ms_3 = QLabel(self.ref_rad_val_est_2)
        self.exp_status_label_ms_3.setObjectName(u"exp_status_label_ms_3")
        self.exp_status_label_ms_3.setGeometry(QRect(240, 30, 90, 30))
        self.exp_status_label_ms_8 = QLabel(self.ref_rad_val_est_2)
        self.exp_status_label_ms_8.setObjectName(u"exp_status_label_ms_8")
        self.exp_status_label_ms_8.setGeometry(QRect(700, 30, 90, 30))
        self.exp_status_label_ms_10 = QLabel(self.ref_rad_val_est_2)
        self.exp_status_label_ms_10.setObjectName(u"exp_status_label_ms_10")
        self.exp_status_label_ms_10.setGeometry(QRect(1160, 30, 90, 30))
        self.exp_status_label_ms_11 = QLabel(self.ref_rad_val_est_2)
        self.exp_status_label_ms_11.setObjectName(u"exp_status_label_ms_11")
        self.exp_status_label_ms_11.setGeometry(QRect(1620, 30, 90, 30))

        self.retranslateUi(Form)

        # QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.bg_est_2.setTitle(QCoreApplication.translate("Form", u"Dark Noise Estimation", None))
        self.bg_img_dir_2.setText(QCoreApplication.translate("Form", u"Dark Images Source Folder:", None))
        self.bg_img_open_dir_2.setText(QCoreApplication.translate("Form", u"...", None))
        self.bg_img_load_2.setText(QCoreApplication.translate("Form", u"Load Images", None))
        self.bg_img_5.setText("")
        self.bg_img_6.setText("")
        self.bg_img_7.setText("")
        self.bg_img_8.setText("")
        self.bg_noise_est_2.setText(QCoreApplication.translate("Form", u"Estimate Dark Noise Pixel", None))
        self.bg_val_est_2.setTitle(QCoreApplication.translate("Form", u"Dark Noise Values:", None))
        self.bg_b1_2.setText(QCoreApplication.translate("Form", u"BAND 1:", None))
        self.bg_b2_2.setText(QCoreApplication.translate("Form", u"BAND 2:", None))
        self.bg_b3_2.setText(QCoreApplication.translate("Form", u"BAND 3:", None))
        self.bg_b4_2.setText(QCoreApplication.translate("Form", u"BAND 4:", None))
        self.ref_est_2.setTitle(QCoreApplication.translate("Form", u"Reference Radiance Estimation", None))
        self.ref_img_dir_2.setText(QCoreApplication.translate("Form", u"Reference Images Source Folder:", None))
        self.ref_img_open_dir_2.setText(QCoreApplication.translate("Form", u"...", None))
        self.ref_img_load_2.setText(QCoreApplication.translate("Form", u"Load Images", None))
        self.ref_img_5.setText("")
        self.ref_img_6.setText("")
        self.ref_img_7.setText("")
        self.ref_img_8.setText("")
        self.ref_rad_est_2.setText(QCoreApplication.translate("Form", u"Estimate Reference Radiance", None))
        self.ref_rad_val_est_2.setTitle(QCoreApplication.translate("Form", u"Reference Radiance Values:", None))
        self.ref_rad_b1_2.setText(QCoreApplication.translate("Form", u"BAND 1:", None))
        self.ref_rad_b2_2.setText(QCoreApplication.translate("Form", u"BAND 2:", None))
        self.ref_rad_b3_2.setText(QCoreApplication.translate("Form", u"BAND 3:", None))
        self.ref_rad_b4_2.setText(QCoreApplication.translate("Form", u"BAND 4:", None))
        self.exp_status_label_ms_3.setText(QCoreApplication.translate("Form", u"W sr^-1 m^-2", None))
        self.exp_status_label_ms_8.setText(QCoreApplication.translate("Form", u"W sr^-1 m^-2", None))
        self.exp_status_label_ms_10.setText(QCoreApplication.translate("Form", u"W sr^-1 m^-2", None))
        self.exp_status_label_ms_11.setText(QCoreApplication.translate("Form", u"W sr^-1 m^-2", None))
    # retranslateUi

