# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_CameraViewbGftnS.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QSlider,
    QToolButton, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1896, 1081)
        self.camera_connect_2 = QGroupBox(Form)
        self.camera_connect_2.setObjectName(u"camera_connect_2")
        self.camera_connect_2.setGeometry(QRect(10, 0, 391, 195))
        font = QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        self.camera_connect_2.setFont(font)
        self.router_ip_add_2 = QLabel(self.camera_connect_2)
        self.router_ip_add_2.setObjectName(u"router_ip_add_2")
        self.router_ip_add_2.setGeometry(QRect(11, 32, 129, 22))
        self.router_ip_add_in_2 = QLineEdit(self.camera_connect_2)
        self.router_ip_add_in_2.setObjectName(u"router_ip_add_in_2")
        self.router_ip_add_in_2.setGeometry(QRect(11, 60, 371, 26))
        self.cam_ip_add_2 = QLabel(self.camera_connect_2)
        self.cam_ip_add_2.setObjectName(u"cam_ip_add_2")
        self.cam_ip_add_2.setGeometry(QRect(11, 92, 136, 22))
        self.cam_ip_add_in_2 = QLineEdit(self.camera_connect_2)
        self.cam_ip_add_in_2.setObjectName(u"cam_ip_add_in_2")
        self.cam_ip_add_in_2.setGeometry(QRect(11, 120, 371, 26))
        self.detect_2 = QPushButton(self.camera_connect_2)
        self.detect_2.setObjectName(u"detect_2")
        self.detect_2.setGeometry(QRect(183, 152, 81, 32))
        self.connect_2 = QPushButton(self.camera_connect_2)
        self.connect_2.setObjectName(u"connect_2")
        self.connect_2.setGeometry(QRect(300, 152, 81, 32))
        self.cam_view_5 = QGroupBox(Form)
        self.cam_view_5.setObjectName(u"cam_view_5")
        self.cam_view_5.setGeometry(QRect(411, 0, 730, 521))
        self.cam_view_5.setFont(font)
        self.cam_image_2 = QLabel(self.cam_view_5)
        self.cam_image_2.setObjectName(u"cam_image_2")
        self.cam_image_2.setGeometry(QRect(10, 60, 631, 441))
        self.gain_slide_2 = QSlider(self.cam_view_5)
        self.gain_slide_2.setObjectName(u"gain_slide_2")
        self.gain_slide_2.setGeometry(QRect(680, 50, 20, 201))
        self.gain_slide_2.setFont(font)
        self.gain_slide_2.setMaximum(33)
        self.gain_slide_2.setPageStep(0)
        self.gain_slide_2.setOrientation(Qt.Orientation.Vertical)
        self.gain_slide_2.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_slide_2 = QSlider(self.cam_view_5)
        self.exp_slide_2.setObjectName(u"exp_slide_2")
        self.exp_slide_2.setGeometry(QRect(680, 300, 20, 201))
        self.exp_slide_2.setFont(font)
        self.exp_slide_2.setMinimum(1)
        self.exp_slide_2.setMaximum(12)
        self.exp_slide_2.setPageStep(0)
        self.exp_slide_2.setValue(1)
        self.exp_slide_2.setOrientation(Qt.Orientation.Vertical)
        self.exp_slide_2.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_2 = QLabel(self.cam_view_5)
        self.exp_2.setObjectName(u"exp_2")
        self.exp_2.setGeometry(QRect(660, 270, 60, 29))
        self.exp_2.setFont(font)
        self.gain_2 = QLabel(self.cam_view_5)
        self.gain_2.setObjectName(u"gain_2")
        self.gain_2.setGeometry(QRect(670, 20, 40, 29))
        self.gain_2.setFont(font)
        self.gain_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gain_status_label_2 = QLabel(self.cam_view_5)
        self.gain_status_label_2.setObjectName(u"gain_status_label_2")
        self.gain_status_label_2.setGeometry(QRect(10, 20, 29, 30))
        self.gain_status_2 = QLabel(self.cam_view_5)
        self.gain_status_2.setObjectName(u"gain_status_2")
        self.gain_status_2.setGeometry(QRect(40, 20, 41, 30))
        self.exp_status_label_2 = QLabel(self.cam_view_5)
        self.exp_status_label_2.setObjectName(u"exp_status_label_2")
        self.exp_status_label_2.setGeometry(QRect(100, 20, 30, 30))
        self.exp_status_2 = QLabel(self.cam_view_5)
        self.exp_status_2.setObjectName(u"exp_status_2")
        self.exp_status_2.setGeometry(QRect(130, 20, 41, 30))
        self.exp_status_label_ms_3 = QLabel(self.cam_view_5)
        self.exp_status_label_ms_3.setObjectName(u"exp_status_label_ms_3")
        self.exp_status_label_ms_3.setGeometry(QRect(180, 20, 20, 30))
        self.cam_view_6 = QGroupBox(Form)
        self.cam_view_6.setObjectName(u"cam_view_6")
        self.cam_view_6.setGeometry(QRect(1161, 0, 731, 521))
        self.cam_view_6.setFont(font)
        self.cam_image_10 = QLabel(self.cam_view_6)
        self.cam_image_10.setObjectName(u"cam_image_10")
        self.cam_image_10.setGeometry(QRect(10, 60, 631, 441))
        self.gain_slide_10 = QSlider(self.cam_view_6)
        self.gain_slide_10.setObjectName(u"gain_slide_10")
        self.gain_slide_10.setGeometry(QRect(680, 50, 20, 201))
        self.gain_slide_10.setFont(font)
        self.gain_slide_10.setMaximum(33)
        self.gain_slide_10.setPageStep(0)
        self.gain_slide_10.setOrientation(Qt.Orientation.Vertical)
        self.gain_slide_10.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_slide_10 = QSlider(self.cam_view_6)
        self.exp_slide_10.setObjectName(u"exp_slide_10")
        self.exp_slide_10.setGeometry(QRect(680, 300, 20, 201))
        self.exp_slide_10.setFont(font)
        self.exp_slide_10.setMinimum(1)
        self.exp_slide_10.setMaximum(12)
        self.exp_slide_10.setPageStep(0)
        self.exp_slide_10.setValue(1)
        self.exp_slide_10.setOrientation(Qt.Orientation.Vertical)
        self.exp_slide_10.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_10 = QLabel(self.cam_view_6)
        self.exp_10.setObjectName(u"exp_10")
        self.exp_10.setGeometry(QRect(660, 270, 60, 29))
        self.exp_10.setFont(font)
        self.gain_10 = QLabel(self.cam_view_6)
        self.gain_10.setObjectName(u"gain_10")
        self.gain_10.setGeometry(QRect(670, 20, 40, 29))
        self.gain_10.setFont(font)
        self.gain_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gain_status_label_10 = QLabel(self.cam_view_6)
        self.gain_status_label_10.setObjectName(u"gain_status_label_10")
        self.gain_status_label_10.setGeometry(QRect(10, 20, 30, 30))
        self.gain_status_10 = QLabel(self.cam_view_6)
        self.gain_status_10.setObjectName(u"gain_status_10")
        self.gain_status_10.setGeometry(QRect(40, 20, 41, 30))
        self.exp_status_label_10 = QLabel(self.cam_view_6)
        self.exp_status_label_10.setObjectName(u"exp_status_label_10")
        self.exp_status_label_10.setGeometry(QRect(100, 20, 30, 30))
        self.exp_status_10 = QLabel(self.cam_view_6)
        self.exp_status_10.setObjectName(u"exp_status_10")
        self.exp_status_10.setGeometry(QRect(130, 20, 41, 30))
        self.exp_status_label_ms_10 = QLabel(self.cam_view_6)
        self.exp_status_label_ms_10.setObjectName(u"exp_status_label_ms_10")
        self.exp_status_label_ms_10.setGeometry(QRect(180, 20, 20, 30))
        self.cam_view_7 = QGroupBox(Form)
        self.cam_view_7.setObjectName(u"cam_view_7")
        self.cam_view_7.setGeometry(QRect(411, 550, 731, 521))
        self.cam_view_7.setFont(font)
        self.cam_image_14 = QLabel(self.cam_view_7)
        self.cam_image_14.setObjectName(u"cam_image_14")
        self.cam_image_14.setGeometry(QRect(10, 60, 631, 441))
        self.gain_slide_14 = QSlider(self.cam_view_7)
        self.gain_slide_14.setObjectName(u"gain_slide_14")
        self.gain_slide_14.setGeometry(QRect(680, 50, 20, 201))
        self.gain_slide_14.setFont(font)
        self.gain_slide_14.setMaximum(33)
        self.gain_slide_14.setPageStep(0)
        self.gain_slide_14.setOrientation(Qt.Orientation.Vertical)
        self.gain_slide_14.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_slide_14 = QSlider(self.cam_view_7)
        self.exp_slide_14.setObjectName(u"exp_slide_14")
        self.exp_slide_14.setGeometry(QRect(680, 300, 20, 201))
        self.exp_slide_14.setFont(font)
        self.exp_slide_14.setMinimum(1)
        self.exp_slide_14.setMaximum(12)
        self.exp_slide_14.setPageStep(0)
        self.exp_slide_14.setValue(1)
        self.exp_slide_14.setOrientation(Qt.Orientation.Vertical)
        self.exp_slide_14.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_14 = QLabel(self.cam_view_7)
        self.exp_14.setObjectName(u"exp_14")
        self.exp_14.setGeometry(QRect(660, 270, 60, 29))
        self.exp_14.setFont(font)
        self.gain_14 = QLabel(self.cam_view_7)
        self.gain_14.setObjectName(u"gain_14")
        self.gain_14.setGeometry(QRect(670, 20, 40, 29))
        self.gain_14.setFont(font)
        self.gain_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gain_status_label_14 = QLabel(self.cam_view_7)
        self.gain_status_label_14.setObjectName(u"gain_status_label_14")
        self.gain_status_label_14.setGeometry(QRect(10, 30, 29, 30))
        self.gain_status_14 = QLabel(self.cam_view_7)
        self.gain_status_14.setObjectName(u"gain_status_14")
        self.gain_status_14.setGeometry(QRect(40, 30, 41, 30))
        self.exp_status_label_14 = QLabel(self.cam_view_7)
        self.exp_status_label_14.setObjectName(u"exp_status_label_14")
        self.exp_status_label_14.setGeometry(QRect(100, 30, 19, 30))
        self.exp_status_14 = QLabel(self.cam_view_7)
        self.exp_status_14.setObjectName(u"exp_status_14")
        self.exp_status_14.setGeometry(QRect(130, 30, 41, 30))
        self.exp_status_label_ms_14 = QLabel(self.cam_view_7)
        self.exp_status_label_ms_14.setObjectName(u"exp_status_label_ms_14")
        self.exp_status_label_ms_14.setGeometry(QRect(180, 30, 20, 30))
        self.image_save_5 = QGroupBox(Form)
        self.image_save_5.setObjectName(u"image_save_5")
        self.image_save_5.setGeometry(QRect(10, 928, 391, 131))
        self.image_save_5.setFont(font)
        self.folder_save_path_5 = QLineEdit(self.image_save_5)
        self.folder_save_path_5.setObjectName(u"folder_save_path_5")
        self.folder_save_path_5.setGeometry(QRect(11, 63, 331, 26))
        self.img_dir_5 = QLabel(self.image_save_5)
        self.img_dir_5.setObjectName(u"img_dir_5")
        self.img_dir_5.setGeometry(QRect(11, 32, 103, 22))
        self.img_save_act_5 = QCheckBox(self.image_save_5)
        self.img_save_act_5.setObjectName(u"img_save_act_5")
        self.img_save_act_5.setGeometry(QRect(241, 96, 139, 24))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_save_act_5.sizePolicy().hasHeightForWidth())
        self.img_save_act_5.setSizePolicy(sizePolicy)
        self.folder_save_open_dir_5 = QToolButton(self.image_save_5)
        self.folder_save_open_dir_5.setObjectName(u"folder_save_open_dir_5")
        self.folder_save_open_dir_5.setGeometry(QRect(354, 62, 26, 28))
        self.cam_view_8 = QGroupBox(Form)
        self.cam_view_8.setObjectName(u"cam_view_8")
        self.cam_view_8.setGeometry(QRect(1161, 550, 731, 521))
        self.cam_view_8.setFont(font)
        self.cam_image_15 = QLabel(self.cam_view_8)
        self.cam_image_15.setObjectName(u"cam_image_15")
        self.cam_image_15.setGeometry(QRect(10, 60, 631, 441))
        self.gain_slide_15 = QSlider(self.cam_view_8)
        self.gain_slide_15.setObjectName(u"gain_slide_15")
        self.gain_slide_15.setGeometry(QRect(680, 50, 20, 201))
        self.gain_slide_15.setFont(font)
        self.gain_slide_15.setMaximum(33)
        self.gain_slide_15.setPageStep(0)
        self.gain_slide_15.setOrientation(Qt.Orientation.Vertical)
        self.gain_slide_15.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_slide_15 = QSlider(self.cam_view_8)
        self.exp_slide_15.setObjectName(u"exp_slide_15")
        self.exp_slide_15.setGeometry(QRect(680, 300, 20, 201))
        self.exp_slide_15.setFont(font)
        self.exp_slide_15.setMinimum(1)
        self.exp_slide_15.setMaximum(12)
        self.exp_slide_15.setPageStep(0)
        self.exp_slide_15.setValue(1)
        self.exp_slide_15.setOrientation(Qt.Orientation.Vertical)
        self.exp_slide_15.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.exp_15 = QLabel(self.cam_view_8)
        self.exp_15.setObjectName(u"exp_15")
        self.exp_15.setGeometry(QRect(660, 270, 60, 29))
        self.exp_15.setFont(font)
        self.gain_15 = QLabel(self.cam_view_8)
        self.gain_15.setObjectName(u"gain_15")
        self.gain_15.setGeometry(QRect(670, 20, 40, 29))
        self.gain_15.setFont(font)
        self.gain_15.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gain_status_label_15 = QLabel(self.cam_view_8)
        self.gain_status_label_15.setObjectName(u"gain_status_label_15")
        self.gain_status_label_15.setGeometry(QRect(10, 30, 30, 30))
        self.gain_status_15 = QLabel(self.cam_view_8)
        self.gain_status_15.setObjectName(u"gain_status_15")
        self.gain_status_15.setGeometry(QRect(40, 30, 41, 30))
        self.exp_status_label_15 = QLabel(self.cam_view_8)
        self.exp_status_label_15.setObjectName(u"exp_status_label_15")
        self.exp_status_label_15.setGeometry(QRect(100, 30, 30, 30))
        self.exp_status_15 = QLabel(self.cam_view_8)
        self.exp_status_15.setObjectName(u"exp_status_15")
        self.exp_status_15.setGeometry(QRect(130, 30, 41, 30))
        self.exp_status_label_ms_15 = QLabel(self.cam_view_8)
        self.exp_status_label_ms_15.setObjectName(u"exp_status_label_ms_15")
        self.exp_status_label_ms_15.setGeometry(QRect(180, 30, 20, 30))
        self.image_overlay_2 = QGroupBox(Form)
        self.image_overlay_2.setObjectName(u"image_overlay_2")
        self.image_overlay_2.setGeometry(QRect(10, 804, 391, 91))
        self.image_overlay_2.setFont(font)
        self.img_overlay_open_2 = QPushButton(self.image_overlay_2)
        self.img_overlay_open_2.setObjectName(u"img_overlay_open_2")
        self.img_overlay_open_2.setGeometry(QRect(11, 40, 210, 32))
        self.img_overlay_act_2 = QCheckBox(self.image_overlay_2)
        self.img_overlay_act_2.setObjectName(u"img_overlay_act_2")
        self.img_overlay_act_2.setGeometry(QRect(256, 44, 124, 24))

        self.retranslateUi(Form)

        # QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.camera_connect_2.setTitle(QCoreApplication.translate("Form", u"Connecting Camera...", None))
        self.router_ip_add_2.setText(QCoreApplication.translate("Form", u"Router IP Address:", None))
        self.cam_ip_add_2.setText(QCoreApplication.translate("Form", u"Camera IP Address:", None))
        self.detect_2.setText(QCoreApplication.translate("Form", u"Detect", None))
        self.connect_2.setText(QCoreApplication.translate("Form", u"Connect", None))
        self.cam_view_5.setTitle(QCoreApplication.translate("Form", u"CAM 1", None))
        self.cam_image_2.setText(QCoreApplication.translate("Form", u"CAMERA 1", None))
        self.exp_2.setText(QCoreApplication.translate("Form", u"Exp (ms)", None))
        self.gain_2.setText(QCoreApplication.translate("Form", u"Gain", None))
        self.gain_status_label_2.setText(QCoreApplication.translate("Form", u"G =", None))
        self.gain_status_2.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_2.setText(QCoreApplication.translate("Form", u"E =", None))
        self.exp_status_2.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_ms_3.setText(QCoreApplication.translate("Form", u"ms", None))
        self.cam_view_6.setTitle(QCoreApplication.translate("Form", u"CAM 2", None))
        self.cam_image_10.setText(QCoreApplication.translate("Form", u"CAMERA 2", None))
        self.exp_10.setText(QCoreApplication.translate("Form", u"Exp (ms)", None))
        self.gain_10.setText(QCoreApplication.translate("Form", u"Gain", None))
        self.gain_status_label_10.setText(QCoreApplication.translate("Form", u"G =", None))
        self.gain_status_10.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_10.setText(QCoreApplication.translate("Form", u"E =", None))
        self.exp_status_10.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_ms_10.setText(QCoreApplication.translate("Form", u"ms", None))
        self.cam_view_7.setTitle(QCoreApplication.translate("Form", u"CAM 3", None))
        self.cam_image_14.setText(QCoreApplication.translate("Form", u"CAMERA 3", None))
        self.exp_14.setText(QCoreApplication.translate("Form", u"Exp (ms)", None))
        self.gain_14.setText(QCoreApplication.translate("Form", u"Gain", None))
        self.gain_status_label_14.setText(QCoreApplication.translate("Form", u"G =", None))
        self.gain_status_14.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_14.setText(QCoreApplication.translate("Form", u"E =", None))
        self.exp_status_14.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_ms_14.setText(QCoreApplication.translate("Form", u"ms", None))
        self.image_save_5.setTitle(QCoreApplication.translate("Form", u"Raw Image Save", None))
        self.img_dir_5.setText(QCoreApplication.translate("Form", u"Output Folder:", None))
        self.img_save_act_5.setText(QCoreApplication.translate("Form", u"  Save Image(s)", None))
        self.folder_save_open_dir_5.setText(QCoreApplication.translate("Form", u"...", None))
        self.cam_view_8.setTitle(QCoreApplication.translate("Form", u"CAM 4", None))
        self.cam_image_15.setText(QCoreApplication.translate("Form", u"CAMERA 4", None))
        self.exp_15.setText(QCoreApplication.translate("Form", u"Exp (ms)", None))
        self.gain_15.setText(QCoreApplication.translate("Form", u"Gain", None))
        self.gain_status_label_15.setText(QCoreApplication.translate("Form", u"G =", None))
        self.gain_status_15.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_15.setText(QCoreApplication.translate("Form", u"E =", None))
        self.exp_status_15.setText(QCoreApplication.translate("Form", u"...", None))
        self.exp_status_label_ms_15.setText(QCoreApplication.translate("Form", u"ms", None))
        self.image_overlay_2.setTitle(QCoreApplication.translate("Form", u"Raw Image Alignment", None))
        self.img_overlay_open_2.setText(QCoreApplication.translate("Form", u"Image Alignment Settings", None))
        self.img_overlay_act_2.setText(QCoreApplication.translate("Form", u"Align Images", None))
    # retranslateUi

