# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_RasterCalculationAwpZBB.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QGroupBox, QLabel, QLineEdit, QListView,
    QPlainTextEdit, QPushButton, QSizePolicy, QToolButton,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1901, 1096)
        self.refl_est = QGroupBox(Form)
        self.refl_est.setObjectName(u"refl_est")
        self.refl_est.setGeometry(QRect(10, 10, 911, 1071))
        font = QFont()
        font.setPointSize(12)
        self.refl_est.setFont(font)
        self.refl_val_est = QPushButton(self.refl_est)
        self.refl_val_est.setObjectName(u"refl_val_est")
        self.refl_val_est.setGeometry(QRect(10, 30, 180, 40))
        self.refl_img_1 = QLabel(self.refl_est)
        self.refl_img_1.setObjectName(u"refl_img_1")
        self.refl_img_1.setGeometry(QRect(10, 150, 440, 321))
        self.refl_img_2 = QLabel(self.refl_est)
        self.refl_img_2.setObjectName(u"refl_img_2")
        self.refl_img_2.setGeometry(QRect(460, 150, 440, 321))
        self.refl_img_4 = QLabel(self.refl_est)
        self.refl_img_4.setObjectName(u"refl_img_4")
        self.refl_img_4.setGeometry(QRect(460, 480, 440, 321))
        self.refl_img_3 = QLabel(self.refl_est)
        self.refl_img_3.setObjectName(u"refl_img_3")
        self.refl_img_3.setGeometry(QRect(10, 480, 440, 321))
        self.image_save_2 = QGroupBox(self.refl_est)
        self.image_save_2.setObjectName(u"image_save_2")
        self.image_save_2.setGeometry(QRect(520, 910, 371, 141))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setUnderline(False)
        self.image_save_2.setFont(font1)
        self.img_save_act_2 = QCheckBox(self.image_save_2)
        self.img_save_act_2.setObjectName(u"img_save_act_2")
        self.img_save_act_2.setGeometry(QRect(230, 110, 140, 31))
        self.folder_save_open_dir_2 = QToolButton(self.image_save_2)
        self.folder_save_open_dir_2.setObjectName(u"folder_save_open_dir_2")
        self.folder_save_open_dir_2.setGeometry(QRect(330, 70, 31, 31))
        self.folder_save_path_2 = QLineEdit(self.image_save_2)
        self.folder_save_path_2.setObjectName(u"folder_save_path_2")
        self.folder_save_path_2.setGeometry(QRect(10, 70, 310, 31))
        self.img_dir_2 = QLabel(self.image_save_2)
        self.img_dir_2.setObjectName(u"img_dir_2")
        self.img_dir_2.setGeometry(QRect(10, 30, 110, 31))
        self.ras_est = QGroupBox(Form)
        self.ras_est.setObjectName(u"ras_est")
        self.ras_est.setGeometry(QRect(950, 10, 940, 1071))
        self.ras_est.setFont(font)
        self.ras_img = QLabel(self.ras_est)
        self.ras_img.setObjectName(u"ras_img")
        self.ras_img.setGeometry(QRect(140, 420, 581, 461))
        self.ras_band_list = QListView(self.ras_est)
        self.ras_band_list.setObjectName(u"ras_band_list")
        self.ras_band_list.setGeometry(QRect(10, 70, 271, 251))
        self.ras_band_list_lbl = QLabel(self.ras_est)
        self.ras_band_list_lbl.setObjectName(u"ras_band_list_lbl")
        self.ras_band_list_lbl.setGeometry(QRect(10, 30, 120, 30))
        self.ras_func_lbl = QLabel(self.ras_est)
        self.ras_func_lbl.setObjectName(u"ras_func_lbl")
        self.ras_func_lbl.setGeometry(QRect(330, 30, 130, 30))
        self.ras_func_txt = QPlainTextEdit(self.ras_est)
        self.ras_func_txt.setObjectName(u"ras_func_txt")
        self.ras_func_txt.setGeometry(QRect(330, 70, 601, 251))
        self.ras_check_func = QPushButton(self.ras_est)
        self.ras_check_func.setObjectName(u"ras_check_func")
        self.ras_check_func.setGeometry(QRect(760, 330, 80, 30))
        self.ras_reset_func = QPushButton(self.ras_est)
        self.ras_reset_func.setObjectName(u"ras_reset_func")
        self.ras_reset_func.setGeometry(QRect(330, 330, 80, 30))
        self.ras_apply_func = QPushButton(self.ras_est)
        self.ras_apply_func.setObjectName(u"ras_apply_func")
        self.ras_apply_func.setGeometry(QRect(850, 330, 80, 30))
        self.vis_set = QGroupBox(self.ras_est)
        self.vis_set.setObjectName(u"vis_set")
        self.vis_set.setGeometry(QRect(20, 910, 371, 141))
        self.vis_colormap = QLabel(self.vis_set)
        self.vis_colormap.setObjectName(u"vis_colormap")
        self.vis_colormap.setGeometry(QRect(10, 30, 80, 30))
        self.vis_vmin = QLabel(self.vis_set)
        self.vis_vmin.setObjectName(u"vis_vmin")
        self.vis_vmin.setGeometry(QRect(10, 90, 40, 30))
        self.vis_vmax = QLabel(self.vis_set)
        self.vis_vmax.setObjectName(u"vis_vmax")
        self.vis_vmax.setGeometry(QRect(200, 90, 40, 30))
        self.vis_colormap_list = QComboBox(self.vis_set)
        self.vis_colormap_list.setObjectName(u"vis_colormap_list")
        self.vis_colormap_list.setGeometry(QRect(90, 30, 271, 30))
        self.vis_vmin_val = QDoubleSpinBox(self.vis_set)
        self.vis_vmin_val.setObjectName(u"vis_vmin_val")
        self.vis_vmin_val.setGeometry(QRect(70, 90, 101, 30))
        self.vis_vmax_val = QDoubleSpinBox(self.vis_set)
        self.vis_vmax_val.setObjectName(u"vis_vmax_val")
        self.vis_vmax_val.setGeometry(QRect(260, 90, 101, 30))
        self.ras_calc = QLabel(self.ras_est)
        self.ras_calc.setObjectName(u"ras_calc")
        self.ras_calc.setGeometry(QRect(10, 370, 140, 30))
        self.ras_calc_list = QComboBox(self.ras_est)
        self.ras_calc_list.setObjectName(u"ras_calc_list")
        self.ras_calc_list.setGeometry(QRect(140, 370, 91, 30))
        self.image_save_3 = QGroupBox(self.ras_est)
        self.image_save_3.setObjectName(u"image_save_3")
        self.image_save_3.setGeometry(QRect(550, 910, 371, 141))
        self.image_save_3.setFont(font1)
        self.img_save_act_3 = QCheckBox(self.image_save_3)
        self.img_save_act_3.setObjectName(u"img_save_act_3")
        self.img_save_act_3.setGeometry(QRect(230, 110, 140, 31))
        self.folder_save_open_dir_3 = QToolButton(self.image_save_3)
        self.folder_save_open_dir_3.setObjectName(u"folder_save_open_dir_3")
        self.folder_save_open_dir_3.setGeometry(QRect(330, 70, 31, 31))
        self.folder_save_path_3 = QLineEdit(self.image_save_3)
        self.folder_save_path_3.setObjectName(u"folder_save_path_3")
        self.folder_save_path_3.setGeometry(QRect(10, 70, 311, 31))
        self.img_dir_3 = QLabel(self.image_save_3)
        self.img_dir_3.setObjectName(u"img_dir_3")
        self.img_dir_3.setGeometry(QRect(10, 30, 110, 31))
        self.img_leg = QLabel(self.ras_est)
        self.img_leg.setObjectName(u"img_leg")
        self.img_leg.setGeometry(QRect(760, 420, 71, 461))

        self.retranslateUi(Form)

        #QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.refl_est.setTitle(QCoreApplication.translate("Form", u"Reflectance Estimation", None))
        self.refl_val_est.setText(QCoreApplication.translate("Form", u"Calculate Reflectance", None))
        self.refl_img_1.setText("")
        self.refl_img_2.setText("")
        self.refl_img_4.setText("")
        self.refl_img_3.setText("")
        self.image_save_2.setTitle(QCoreApplication.translate("Form", u"Reflectance Image Save", None))
        self.img_save_act_2.setText(QCoreApplication.translate("Form", u"  Save Image(s)", None))
        self.folder_save_open_dir_2.setText(QCoreApplication.translate("Form", u"...", None))
        self.img_dir_2.setText(QCoreApplication.translate("Form", u"Output Folder:", None))
        self.ras_est.setTitle(QCoreApplication.translate("Form", u"Raster Calculation", None))
        self.ras_img.setText("")
        self.ras_band_list_lbl.setText(QCoreApplication.translate("Form", u"Raster Band List: ", None))
        self.ras_func_lbl.setText(QCoreApplication.translate("Form", u"Raster Expression: ", None))
        self.ras_check_func.setText(QCoreApplication.translate("Form", u"Check", None))
        self.ras_reset_func.setText(QCoreApplication.translate("Form", u"Reset", None))
        self.ras_apply_func.setText(QCoreApplication.translate("Form", u"Apply", None))
        self.vis_set.setTitle(QCoreApplication.translate("Form", u"Visual Settings", None))
        self.vis_colormap.setText(QCoreApplication.translate("Form", u"Colormap:", None))
        self.vis_vmin.setText(QCoreApplication.translate("Form", u"Vmin:", None))
        self.vis_vmax.setText(QCoreApplication.translate("Form", u"Vmax:", None))
        self.ras_calc.setText(QCoreApplication.translate("Form", u"Calculated Raster:", None))
        self.image_save_3.setTitle(QCoreApplication.translate("Form", u"Raster Image Save", None))
        self.img_save_act_3.setText(QCoreApplication.translate("Form", u"  Save Image(s)", None))
        self.folder_save_open_dir_3.setText(QCoreApplication.translate("Form", u"...", None))
        self.img_dir_3.setText(QCoreApplication.translate("Form", u"Output Folder:", None))
        self.img_leg.setText("")
    # retranslateUi

